require 'fastercsv'

namespace :mooney do

  desc "Load tests data"
  task :demo => :environment do

    [
      real = Account.new(:name => "C/C REAL"),
      unibanco = Account.new(:name => "C/C UNIBANCO"),
      visa = Account.new(:name => "CART�O VISA"),
      dinheiro = Account.new(:name => "DINHEIRO")
    ].each { |account| account.save }

    puts "== Accounts created ============================"

    Entry.new(:account => real, :date => Time.now, :description => "almoço", :value => -15.55, :paid => true).save
    Entry.new(:account => real, :date => Time.now, :description => "impostos", :value => -415.55, :paid => false).save
    Entry.new(:account => real, :date => Time.now, :description => "salário", :value => 1050.55, :paid => true).save

    puts "== Entries created ============================="

  end

  desc "Import CSV generated file"
  task :csvimport => :environment do
    unless ENV.include?('file') && File.exists?(ENV['file'])
      raise "usage: rake file=<valid file name>" # the file must generated by Mooney
    end

    file = ENV['file']

    user = User.first

    unless user
      raise "No user found"
    end

    FasterCSV.foreach(file, :col_sep =>';', :quote_char => '"', :row_sep => :auto, :headers => true) do |row|
      conta = row['CONTA']
      data = row['DATA']
      account = Account.find_by_name_and_user_id(conta, user.id)
      unless account
        puts "#{conta} does not exist - adding"
        account = Account.new(:name => conta, :user => user)
        account.save
      end

      entry = Entry.new(:account => account, :date => Date.strptime(data, '%d/%m/%Y'), :description => row['DESCRICAO'], :value => row['VALOR'], :paid => row['PAGO'] == 'S', :user => user)
      entry.save
    end

  end

end
